import { VerticalBox , LineEdit, Button, ScrollView, CheckBox, ListView, TabWidget, TextEdit} from "std-widgets.slint";

export global AppStyle {
    out property<length> HEADING_1 :28px;
    out property<length> HEADING_2 :16px;
    out property<length> HEADING_3 :13px;
}

export global BtnLogic {
    pure callback btn-gmod-bin-selection();
    pure callback btn-vtfedit-bin-selection();
    pure callback btn-models-selection();
    pure callback btn-materials-selection();
    pure callback btn-qc_selection();
    pure callback btn-compile();
}

export global FilesPathsLogic {
    in-out property<string> gmod_bin_path;
    in-out property<string> vtf_bin_path;
    in-out property<string> models_path;
    in-out property<string> materials_path;
    in-out property<string> compilation_out_path;
}


export global TextLogic {
    in-out property<string> logs;
    in-out property<string> qc_file_viewer;
    in-out property<string> gmod_bin_verif_text;
}

component AppBox inherits Rectangle {
    background: #10141D80;
    //opacity: 50%;
    border-radius: 25px;
    border-color: #981764;
    border-width: 2px;
    /*drop-shadow-color: #981764;
    drop-shadow-blur: 5px;
    drop-shadow-offset-y: 5px;*/
}
component AppPage inherits GridLayout {
    spacing: 10px;
    padding: 10px;
    @children
    AppBox {
        row: 4;
        colspan: 4;
        VerticalLayout {

            padding: 10px;
            padding-left: 20px;
            padding-right: 20px;
            spacing: 10px;
            height: 100%;

            Text {
            text: @tr("text_console_logs");
            color: white;
            font-size: AppStyle.HEADING-2;
            }

            Rectangle {
                background: #00000080;
                ScrollView {
                    viewport-height: parent.height;
                    console_logs := TextInput {
                        input-type: text;
                        color: white;
                        read-only:true;
                        single-line: false;
                        wrap: word-wrap;
                        text: TextLogic.logs;
                    }
                }
            }
        }
    }

}

component Ropes inherits VerticalBox{
    @children
    spacing: 1px;
    Path {
        commands: "M0 192.664C179.238 129.078 320.351 -1.01386 542.243 3.09507C739.141 6.74117 864.924 114.222 1024 169.191 M0 206.332C179.238 142.746 320.351 12.6541 542.243 16.763C739.141 20.4092 864.924 127.89 1024 182.859 M0 220C179.238 156.414 320.351 26.3221 542.243 30.431C739.141 34.0771 864.924 141.558 1024 196.527";
        stroke-width: 5px;
        stroke: #981764;
    }
}

component FileSelection {
    in property<string> text-string;
    in property<string> lineEdit-string;
    callback clicked();
    HorizontalLayout {
        spacing: 10px;

        Text {
        text: text-string;
        color: white;
        vertical-alignment: center;
        }

        path_edit:=LineEdit {
        text: lineEdit-string;
        }

        btn_selec:=Button {
        text: "...";
        clicked => {clicked()}
        }
    }
}

export component App inherits Window {
    title: @tr("gmod_3d_packager");

    min-width: 1024px;
    min-height: 768px;
    //max-width: 1024px;
    //max-height: 768px;

    background: #1E1E1E;

    //Rust


    Ropes{
        width: parent.width;
        height: parent.height;
    }

    TabWidget {
        Tab{
            title: "Props Compile";

            AppPage {
                AppBox { //Files selection
                    row: 0;
                    colspan: 4;
                    VerticalLayout {
                        padding: 10px;
                        padding-left: 20px;
                        padding-right: 20px;
                        spacing: 10px;
                        height: 100%;

                        Text {
                        text: @tr("files_selec_box");
                        color: white;
                        font-size: AppStyle.HEADING_1;
                        }

                        models_selection:=FileSelection {
                            text-string: @tr("text_models_selec");
                            lineEdit-string: FilesPathsLogic.models-path;
                            clicked => {BtnLogic.btn-models-selection()}
                        }
                        materials_selection:= FileSelection {
                            text-string: @tr("text_materials_selec");
                            lineEdit-string: FilesPathsLogic.materials-path;
                            clicked => {BtnLogic.btn-materials-selection()}
                        }

                        out_compile_selection:=FileSelection {
                            text-string: @tr("text_out_selec");
                            lineEdit-string: FilesPathsLogic.compilation-out-path;
                            clicked => {BtnLogic.btn-qc-selection()}
                        }

                        btn_compile:=Button {
                        text: @tr("btn_models_compile");
                        clicked => {BtnLogic.btn-compile()}
                        }
                    }
                }

                AppBox {//QC Infos
                    row: 1;
                    rowspan: 2;
                    col: 0;
                    colspan: 2;
                    padding: 10px;
                    VerticalLayout {
                        padding: 10px;
                        padding-bottom: 20px;
                        padding-left: 20px;
                        padding-right: 20px;
                        spacing: 10px;

                        Text {
                        text: @tr("text_qc_viewer");
                        color: white;
                        font-size: AppStyle.HEADING-2;
                        }

                        Rectangle {
                            background: #00000080;
                            ScrollView {
                                //viewport-height: parent.height;
                                qc_info := TextInput {
                                    input-type: text;
                                    color: white;
                                    read-only:true;
                                    single-line: false;
                                    wrap: word-wrap;
                                    text: TextLogic.qc_file_viewer;
                                }
                            }
                        }
                    }
                }

                /*AppBox {//Compilation options
                    row: 1;
                    rowspan: 2;
                    col: 2;
                    colspan: 2;
                    VerticalLayout {
                        padding: 10px;
                        padding-bottom: 20px;
                        padding-left: 20px;
                        padding-right: 20px;
                        spacing: 10px;
                        height: 100%;

                        Text {
                        text: @tr("text_compile_options");
                        color: white;
                        font-size: AppStyle.HEADING-2;
                        }
                    }
                }*/
            }
        }
        Tab{
        title: "PM Compile";
            AppPage{

            }

        }
        Tab{
        title: "SWEP Compile";
            AppPage{

            }
        }
        Tab{
        title: "Addon Packager";
            AppPage{

            }
        }
        Tab{
        title: @tr("settings");
            AppPage{
                AppBox {
                    row: 0;
                    colspan: 4;
                    VerticalLayout {
                        padding: 10px;
                        padding-bottom: 20px;
                        padding-left: 20px;
                        padding-right: 20px;
                        spacing: 10px;
                        height: 100%;
                        Text {
                            text: @tr("text_bin_settings");
                            color: white;
                            font-size: AppStyle.HEADING-1;
                        }
                        gmod_bin_selection:=FileSelection {
                            text-string: @tr("text_gmod_bin_selec");
                            lineEdit-string: FilesPathsLogic.gmod-bin-path;
                            clicked => {BtnLogic.btn-gmod-bin-selection()}
                        }
                         vtf_bin_selection:=FileSelection {
                            text-string: @tr("text_vtfedit_bin_selec");
                            lineEdit-string: FilesPathsLogic.vtf-bin-path;
                            clicked => {BtnLogic.btn-vtfedit-bin-selection()}
                        }
                        Text {
                            text: @tr("text_gmod_bin_verif");
                            color: white;
                            font-size: AppStyle.HEADING-2;
                        }
                        Rectangle {
                            background: #00000080;
                            ScrollView {
                                //viewport-height: parent.height;
                                bin_verif := TextInput {
                                    input-type: text;
                                    color: white;
                                    read-only:true;
                                    single-line: false;
                                    wrap: word-wrap;
                                    text: TextLogic.gmod_bin_verif_text;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
