on:
  push:
    branches: [ "release" ]

name: Test Build

jobs:
  windows:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --target x86_64-pc-windows-gnu
    
